Update sdk version to tizen_2.2
Change-Id: I1809eee8d9850266ff6811ed982db676235214c8
Signed-off-by: Sangjin Kim <sangjin3.kim@samsung.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -543,6 +543,8 @@ Haiku)
   if [ "$cpu" = "i386" -o "$cpu" = "x86_64" ] ; then
     audio_possible_drivers="$audio_possible_drivers fmod"
   fi
+# fix linking error on Ubuntu 13.04
+  libs_qga="-lrt $libs_qga"
 ;;
 esac
 
@@ -2217,6 +2219,22 @@ else
 fi
 
 ##########################################
+# pixman support probe
+
+if test "$shm" = no; then
+    if $pkg_config pixman-1 > /dev/null 2>&1; then
+        pixman_cflags=`$pkg_config --cflags pixman-1 2>/dev/null`
+        pixman_libs=`$pkg_config --libs pixman-1 2>/dev/null`
+        QEMU_CFLAGS="$pixman_cflags $QEMU_CFLAGS"
+        LIBS="$pixman_libs $LIBS"
+    else
+        echo "Error: pixman-1 check failed"
+        echo "Make sure to have the pixman-1 libs and headers installed"
+        exit 1
+    fi
+fi
+
+##########################################
 # libcap probe
 
 if test "$cap" != "no" ; then
@@ -2748,7 +2766,10 @@ fi
 cat > $TMPC <<EOF
 #include <signal.h>
 #include <time.h>
+/* Fix linking error on Ubuntu 13.04
 int main(void) { return clock_gettime(CLOCK_REALTIME, NULL); }
+*/
+int main(void) { return timer_gettime(CLOCK_REALTIME, NULL); }
 EOF
 
 if compile_prog "" "" ; then
